const themes = {
  Wireframe: {
    h1: 'black',
    role: 'black',
    'illustration-bg': 'white',
    'illustration-outline': 'black',
    'info-pane': '#F6F6F6',
    'info-icon': 'black',
    'info-title': 'black',
    'info-title-underline': '#E5E5E5',
    'info-subtitle': 'black',
    'info-p': 'black',
    timeline: 'black',
    'timeline-p': 'black',
    'timeline-bg': 'white',
    'job-title': 'black',
    company: '#333333',
    tenure: '#6D6D6D',
    divider: '#D9D9D9',
    'button-fg': 'white',
    'button-bg': '#333333',
    'button-hover': 'black',
  },
  'Blue Steel': {
    h1: '#082548',
    role: '#244B79',
    'illustration-bg': 'white',
    'illustration-outline': '#082548',
    'info-pane': '#C7D5E7',
    'info-icon': '#082548',
    'info-title': '#082548',
    'info-title-underline': '#082548',
    'info-subtitle': '#082548',
    'info-p': '#082548',
    timeline: '#082548',
    'timeline-p': '#2B2B2B',
    'timeline-bg': 'white',
    'job-title': '#244B79',
    company: '#333333',
    tenure: '#6D6D6D',
    divider: '#D9D9D9',
    'button-fg': '#ffffff',
    'button-bg': '#244B79',
    'button-hover': '#082548',
  },
  'Peach Berry': {
    h1: '#3D0834',
    role: '#3D0834',
    'illustration-bg': 'white',
    'illustration-outline': '#3D0834',
    'info-pane': '#FFD9CD',
    'info-icon': '#3D0834',
    'info-title': '#3D0834',
    'info-title-underline': '#D79581',
    'info-subtitle': '#3D0834',
    'info-p': '#3D0834',
    timeline: '#3D0834',
    'timeline-p': 'black',
    'timeline-bg': '#FFFBFA',
    'job-title': '#990A60',
    company: 'black',
    tenure: '#6D6D6D',
    divider: '#FFD9CD',
    'button-fg': '#ffffff',
    'button-bg': '#990A60',
    'button-hover': '#3D0834',
  },
  Magma: {
    h1: '#C14953',
    role: '#F2EAD6',
    'illustration-bg': '#F2EAD6',
    'illustration-outline': 'black',
    'info-pane': '#4C4C47',
    'info-icon': '#F2EAD6',
    'info-title': '#F2EAD6',
    'info-title-underline': '#C14953',
    'info-subtitle': '#F2EAD6',
    'info-p': '#F2EAD6',
    timeline: '#C14953',
    'timeline-p': '#F2EAD6',
    'timeline-bg': '#2D2D2A',
    'job-title': '#C14953',
    company: '#F2EAD6',
    tenure: '#C7D5E6',
    divider: '#C7D5E6',
    'button-fg': '#2D2D2A',
    'button-bg': '#F2EAD6',
    'button-hover': '#C7D5E6',
  },
  'Night Lime': {
    h1: '#9AE19D',
    role: 'white',
    'illustration-bg': '#909590',
    'illustration-outline': 'black',
    'info-pane': '#474A48',
    'info-icon': '#9AE19D',
    'info-title': 'white',
    'info-title-underline': '#9AE19D',
    'info-subtitle': 'white',
    'info-p': 'white',
    timeline: '#9AE19D',
    'timeline-p': 'white',
    'timeline-bg': '#2C302E',
    'job-title': '#9AE19D',
    company: 'white',
    tenure: '#909590',
    divider: '#909590',
    'button-fg': '#2C302E',
    'button-bg': 'white',
    'button-hover': '#9AE19D',
  },
};

export default themes;
